import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import puppeteer from "puppeteer";

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_GENAPI_KEY,
});

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `You are an expert technical interviewer and career coach.
Analyze the candidate's resume, self-description, and job description.
Return ONLY a valid JSON object. No markdown, no code blocks, no explanation.

{
  "matchScore": <number 0-100>,
  "title": <titleOfThisReport>
  "technicalQuestions": [
    {
      "question": "<question text>",
      "intention": "<why interviewer asks this>",
      "answer": "<how to answer with key points>"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "<question text>",
      "intention": "<why interviewer asks this>",
      "answer": "<how to answer with key points>"
    }
  ],
  "skillGap": [
    {
      "skill": "<skill name>",
      "severity": "<low|medium|high>"
    }
  ],
  "preparationPlan": [
    {
      "day": <number>,
      "focus": "<focus area>",
      "task": ["<task 1>", "<task 2>"]
    }
  ]
}

Rules:
- 4 technical questions
- 2-3 behavioral questions
- all skill gaps with severity
- 5 day preparation plan, tasks must be an array of strings
- all keys must be lowercase exactly as shown above

Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}`;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json", // no responseJsonSchema — this was causing the conflict
    },
  });

  const raw = JSON.parse(response.text);

  return {
    matchScore: raw.matchScore,
    title: raw.title,
    technicalQuestions: raw.technicalQuestions.map((item) => ({
      question: item.question || "",
      intention: item.intention || "",
      answer: item.answer || "",
    })),
    behavioralQuestions: raw.behavioralQuestions.map((item) => ({
      question: item.question || "",
      intention: item.intention || "",
      answer: item.answer || "",
    })),
    skillGap: raw.skillGap.map((item) => ({
      skill: item.skill || "",
      severity: item.severity || "low",
    })),
    preparationPlan: raw.preparationPlan.map((item) => ({
      day: Number(item.day) || 1,
      focus: item.focus || "",
      task: Array.isArray(item.task)
        ? item.task.flat()
        : Array.isArray(item.tasks)
        ? item.tasks.flat()
        : [item.task || item.tasks || ""],
    })),
  };
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch()
  const page = await browser.newPage();
  await page.setContent(htmlContent, {waitUntil: "networkidle0"})

  const pdfBuffer = await page.pdf({format: "A4", margin:{
    top: "10mm",
    bottom: "10mm",
    left: "10mm",
    right: "10mm"
  }});

  await browser.close()

  return pdfBuffer
  
}

async function generateResumePDF({resume, selfDescription, jobDescription}){
  const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
  })
    const prompt = `Generate resume for a candidate with the following details:
    Resume: ${resume}
    Self Description: ${selfDescription}
    Job Description: ${jobDescription}
    
    The response should be JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
    The resume should be Tailored for the given job description and should highlight the candidate's strengths and relevant experience.The HTML content should be well-formatted and structured, making it easy read and visible.
    The content of the resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
    You can highlight the content using colors or different font styles but the overall design should be simple and pofessional.
    The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
    `

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config:{
        responseMimeType: "application/json",
        responseSchema: zodToJsonSchema(resumePdfSchema)
      }
    });

    const jsonContent =  JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

export {generateInterviewReport, generateResumePDF};
